### ISSUE TITLE
[Bug]: Playground authentification from Bitkit widget doesn't work

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1077]
### Describe the bug

From 3 devices we can auth from the [Playground website](https://slashtags.to/playground/accounts) but when we try to login from the SlashAuth Demo Widget, there is a 404 error message.

### Reproduce

1. Go to 'SlashAuth demo widget'
2. Click on 'login'
3. See error

### Screenshots / Recording

![Screenshot_20230526-160015](https://github.com/synonymdev/bitkit/assets/46056211/31abc1ac-b9c6-41f7-b446-c620bd861e90)

### Operating system

Graphene OS and iOS

### Bitkit version

v47

**Comment by MiguelMedeiros** [comment]
Hey @JeanlChristophe !
This issue has already been fixed in this PR: 
https://github.com/synonymdev/slashtags-playground-auth-demo/pull/3

I've already asked @rbndg to update the `slashtags-playground-auth-demo` repository to match the lasted commit.
When the server is updated, you can try again and verify that the authentication redirects to the correct link.

Note: will assign this issue to @rbndg

**Comment by JeanlChristophe** [comment]
Thanks Miguel
