### ISSUE TITLE
{Error] Unable to open Lightning Channel

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1464]
### Describe the bug

tried opening a channel via Quick Setup (size was around 25-30% of total funds) after making sure I had confirmation for on-chain funds, and I get an error (see attachment 

### Screenshots / Recording

![photo_2024-01-05_14-47-14](https://github.com/synonymdev/bitkit/assets/119061223/b0d0b1e2-b508-431e-a63d-115718b59bfd)
![photo_2024-01-05_14-47-12](https://github.com/synonymdev/bitkit/assets/119061223/82ee0d96-6206-4579-b73c-2bc3fbf94fca)

[bitkit_ldk_logs_1704459684242.zip](https://github.com/synonymdev/bitkit/files/13842349/bitkit_ldk_logs_1704459684242.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v93

**Comment by JeanlChristophe** [comment]
it's weird, look about the fees : 0,03$. Current tx are around 50 sat/vb

**Comment by JeanlChristophe** [comment]
v95

I got the same error again, without getting the error message Ttransaction broadcast failed..."

Blocktank received the order but nothing happened afterwards. No transaction was carried out.
The reason was the same error of $0.03 in fees.
order id: 555cae84-f82c-4a55-9c20-ee2f85b211e7
![Screenshot_20240117-122752](https://github.com/synonymdev/bitkit/assets/46056211/dfcb3699-0aee-4cc2-8a99-f282a8589967)
No surprise, the tx isn't find on mempool.
https://mempool.space/tx/b937e6c88190c2294f20148dd0a03e93a7cb209898f4e390412f50d5ba04130b

**Comment by JeanlChristophe** [comment]
Is fixed with beignet migration
