### ISSUE TITLE
Failed payments: Improve copy for error messages

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1555]

**Comment by pwltr** [comment]
Discussed w/ @aldertnl 

@JeanlChristophe 
With the added [hodl invoice UI](https://github.com/synonymdev/bitkit/pull/1592) the previous error screen won't really show up anymore since we will timeout after 8 seconds showing the pending payment screen (while we keep trying the payment in the background). When the payment finally fails the error will only show up in a toast that says: 'Payment Failed' - 'Your instant payment failed. Please try again.'. Since space is limited in the toast and most of the error messages returned from LN are not useful to the user anyways I think this is fine as the only error message.

I would like to see in practice (after next release) if and how often the error does show up and if we need to improve it. Moving this to backlog until then.

**Comment by JeanlChristophe** [comment]
https://docs.google.com/spreadsheets/d/1oWFQe9Ras8_1UO7cuaQFgQkpJYRr6BtlrsCVWUb5M6k/edit?usp=sharing

**Comment by JeanlChristophe** [comment]
Duplicated https://github.com/orgs/synonymdev/projects/12/views/1?pane=issue&itemId=60183042
