### ISSUE TITLE
[Bug]: Check Balances too soon presents "No funds found" message temporarily

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1681]
### Describe the bug

In the Address Viewer page, if the "Check Balances" button is pressed before addresses are loaded then "No funds found..." message is displayed in the area where the table is to be drawn. Once the addresses have loaded the correct balances are shown.

### Reproduce

1. Go to Settings -> Advanced -> Address Viewer 
2. Before the "Loading Addresses...." goes away, press "Check Balances" button
3. Observe "No funds found under the ..." message

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/0d92211b-8c56-4a27-86c8-dfb95b593f74" width="300">

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v1.0.0-beta.113

**Comment by JeanlChristophe** [comment]
This is not an outcome, but the expected behaviour.
The user is presented with a screen indicating that the addresses are loading.
If the user does not wait for the addresses to be loaded, it is normal for there to be no amount until the scan is complete.

![Image](https://github.com/synonymdev/bitkit/assets/46056211/a2e610e2-62f4-4cb5-94a4-b3f153c91996)

**Comment by catch-21** [comment]
"no funds found" and "up to index -1" is desired behaviour?
