### ISSUE TITLE
Discrepancy between Mempool Market Fee and Bitkit Fee Estimation

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1740]
### Describe the bug

checked the fees in Bitkit - when I click on Custom I can see 50sats / vbyte which is $5.35 according to Bitkit.
In mempool when I see the current fee rate - 56 sats / vbyte is $5.05  (refer to video below)

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/4df75719-7278-43a8-8c4a-ece07bb56aa9

### Operating system

Graphene OS Pixel 6S

### Bitkit version

v115

**Comment by limpbrains** [comment]
This happens because mempool calculates the price for average transaction size, while bitkit takes the actual transaction into account.
The more inputs / outputs you have, the bigger it would be

<img width="249" alt="image" src="https://github.com/synonymdev/bitkit/assets/155891/e20e50e7-bc5f-46f1-a5da-1a027b656886">
