### ISSUE TITLE
[Bug]: Boost fees are not the same on Bitkit and on mempool

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1876]
### Describe the bug

I did a transaction https://mempool.space/tx/05b69d8af651208d14b682f75b77c4bc8e9a2a4b40f47adbd291340b6a07ff8a

and I boosted it https://mempool.space/tx/05b69d8af651208d14b682f75b77c4bc8e9a2a4b40f47adbd291340b6a07ff8a

The fees indicated on mempool are 1494sats but on Bitkit it's 5146sats

### Screenshots / Recording

![Screenshot_20240524-114135](https://github.com/synonymdev/bitkit/assets/46056211/6824e2f5-f964-45e2-ae4f-98486dad8dad)

### Operating system

GrapheneOS

### Bitkit version

118

**Comment by catch-21** [comment]
It is by design to show the sum of all fees for the boost activity, so I think it is ok. In this case it is the fee of these two transactions, 1494+3652=5146 :
- https://mempool.space/tx/05b69d8af651208d14b682f75b77c4bc8e9a2a4b40f47adbd291340b6a07ff8a
- https://mempool.space/tx/94290dc7baf3536ebc8d75d8509c2709f6486c04671f7baa9cca6215d03f82ac

**Comment by pwltr** [comment]
> It is by design to show the sum of all fees for the boost activity, so I think it is ok. In this case it is the fee of these two transactions, 1494+3652=5146 :
> 
> * https://mempool.space/tx/05b69d8af651208d14b682f75b77c4bc8e9a2a4b40f47adbd291340b6a07ff8a
> * https://mempool.space/tx/94290dc7baf3536ebc8d75d8509c2709f6486c04671f7baa9cca6215d03f82ac

I think that assessment is correct. Current implementation looks good to me.
