### ISSUE TITLE
[Feature]: Add ability to switch between sending from savings & spending (unified QR)

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#2003]
### Describe the problem

No way to switch between “Savings” and “Spending” after scanning a unified QR code

### Describe the solution

- [x] Balance Toggle Functionality: It would be nice to allow the sender to switch between “Savings” and “Spending” after scanning a unified QR code (see mockup video)
- [x] Fixed States for Toggle:

	•	For On-chain-only QR codes, the toggle will be set to a fixed “Savings” state (see mockup video).
	•	For Lightning-only invoices, the toggle will be set to a fixed “Spending” state.
	
- [x] Max amount: Added max amount modal with short explanation for end user for when ‘max’ amount is tapped in spending balance send flow. https://synonymworkspace.slack.com/archives/C01H106JRQB/p1712855096363569?thread_ts=1712850323.807499&cid=C01H106JRQB

**Comment by catch-21** [comment]
Tested on v1.0.7 and v1.0.8
Toggles show correctly and work well. Static labels show when they should for onchain address and LN invoiced.
It would be nice to also show the label for lnurl, rraised https://github.com/synonymdev/bitkit/issues/2413
Tapping the available balance to apply max value shows an orange "Reserve Balance" toast message that reads "The maximum spendable amount is a bit lower due to a required reserve balance."
