### ISSUE TITLE
Transfer (v50)

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2081]
This new feature is part of the v50 [#2084 ](https://github.com/synonymdev/bitkit/issues/2084)

New user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228002&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228002&show-proto-sidebar=1&hide-ui=1
Active user: https://www.figma.com/proto/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?page-id=21088%3A222905&node-id=21088-228007&viewport=18%2C229%2C0.13&t=CrpfDpnzVxZoIYii-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21088%3A228007&show-proto-sidebar=1&hide-ui=1

**Transfer:** The Lightning Slider UI is being retired. All Transfer features and flows have been redesigned and optimized (details discussed in UX call).

**Comment by JeanlChristophe** [comment]
Please update #2084 when it's done

**Comment by catch-21** [comment]
Tested on 2e3cf89d424d3f05fe5c2727ab02b3c9f318454a  some feedback:

### 1. Savings page "Transfer To Speanding" button flow doesn't match the design.
#### Design: TRANSFER TO SPENDING (info page) -> TRANSFER TO SPENDING (value input page)
#### Actual: SPENDING BALANCE -> FUND YOUR SPENDING BALANCE -> TRANSFER TO SPENDING (info page)  -> TRANSFER TO SPENDING (value input page)

https://github.com/user-attachments/assets/aa781eae-bbd8-4255-ae5a-e525cfe7134f

- [x] Fixed
- [x] Verified

-----

### 2. Piggy facing wrong way in the Spending page "Transfer To Savings" button flow on TRANSFER TO SAVINGS and PLEASE CONFIRM pages
#### Design: Piggy facing right
#### Actual: Piggy facing left

https://github.com/synonymdev/bitkit/issues/2179

-----

### 3: Piggy placement on Savings page is higher in the design, the top of the piggy ear is at the top boarder and its legs don't touch the button.
#### Design
<img src="https://github.com/user-attachments/assets/e9a81f34-54d7-4bde-9d4b-45581200310f" width="200">

#### Pixel 3a
<img src="https://github.com/user-attachments/assets/a6259f16-083b-4e84-9da3-ac2fb5adf42a" width="200">

#### Poco P3
<img src="https://github.com/user-attachments/assets/231db199-7f0a-4991-af84-0954c6468ab9" width="200">

#### This is similar on the Spending page with the coins, more top margin and more button overlap.
<img src="https://github.com/user-attachments/assets/822bad7d-e03f-495e-89f7-35f7a382aac6" width="200">

https://github.com/synonymdev/bitkit/issues/2180

-----

### 4: Missing coins image on transfer to spending PLEASE CONFIRM page
#### Design: Image of three coins above the Swipe To Transfer slider that is animated to tilt as slider is used 
#### Actual: No image

<img src="https://github.com/user-attachments/assets/0b889e33-9385-46cd-81c6-7b5529b09b5b" width="200">

https://github.com/synonymdev/bitkit/issues/2181

-----

### 5: SELECT FUNDS TO TRANSFER page says I have multiple active Lightning Connections when I only have one. Could change message to say "when you have multiple active Lightning Connections"

<img src="https://github.com/user-attachments/assets/b6dd43c7-8baa-4d88-9a31-40bce5a30b46" width="200">

- [x] Fixed
- [x] Verified

-----

### 6: RECEIVING CAPACITY page starts with no default value, which is invalid and causes error with json in. Should be populated with default value and Continue button should be disabled with no value in entered.

<img src="https://github.com/user-attachments/assets/8092d343-56b2-494f-b0b9-14dd0bed350c" width="200">
<img src="https://github.com/user-attachments/assets/cf59429d-8327-4cf3-9298-3fd000f7d74d" width="200">

- [x] Fixed
- [x] Verified

-----

### 7: RECEIVING CAPACITY page default button sets the value to the same as the spending balance rather than using the value seen on the LIQUIDITY & ROUTING page before this value is overridden.

https://github.com/user-attachments/assets/90629f18-d069-4b5c-8577-dcdcf4f0d971

https://github.com/synonymdev/bitkit/issues/2183

-----

### 8: If custom receiving capacity is set then the value differs on the PLEASE CONFIRM and LIQUIDITY & ROUTING pages, the latter is slightly lower. They should match.

https://github.com/user-attachments/assets/5e0ebcf8-044d-42c1-af78-bfc50d31d8a6

https://github.com/synonymdev/bitkit/issues/2184

-----

### 9: "Channel size too big" error can occur on the TRANSFER TO SPENDING value input page. I suspect this is only when max is selected and Blocktanks maximum changes. The value isn't useful to the user as they only have control of the spending balance here. We could reset the max or improve the error?

https://github.com/user-attachments/assets/24dbcfb0-e5bf-45fc-b39e-b87e8e538696

https://github.com/synonymdev/bitkit/issues/2185

-----

### 10: "Spending Balance Maximum" toast error value can be fraction of a sat, see error:

<img src="https://github.com/user-attachments/assets/aceebe72-1264-468b-973f-d5e48160176f" width="200">

https://github.com/synonymdev/bitkit/issues/2186

-----

### 11: It is possible to create the channel order and swipe to pay after the order has expired (30 minutes). The onchain transaction is still broadcast but channel fails with status 'Order expired'. Can we check the invoice has not expired with a sensible tolerance before broadcasting?

https://github.com/synonymdev/bitkit/issues/2187

-----

**Comment by JeanlChristophe** [comment]
https://github.com/synonymdev/bitkit/issues/2173 I can't scroll when I try to close a channel
