### ISSUE TITLE
[Bug]: RECEIVING CAPACITY page default sets wrong value

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2183]
### Describe the bug

RECEIVING CAPACITY page default button sets the value to the same as the spending balance rather than using the value seen on the LIQUIDITY & ROUTING page before this value is overridden.

### Reproduce

1. Go to LIQUIDITY & ROUTING page
2. Note the receiving capacity value
3. Go to RECEIVING CAPACITY page
4. Tap default button
5. Compare default value with that from LIQUIDITY & ROUTING page
6. Observe the value is different, instead if matches the spending balance value.

### Screenshots / Recording

https://github.com/user-attachments/assets/90629f18-d069-4b5c-8577-dcdcf4f0d971

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

v1.0.4 6404b079a1dd23f079515b3d7a14865baf959914

**Comment by pwltr** [comment]
This is due to the reserve balance being accounted for in the channel graph. There is no right way to do this. Either the graph is wrong in the transfer flow or afterwards in the channel list in the settings. Left a comment in the Figma for @aldertnl

But after https://github.com/synonymdev/bitkit/pull/2169 the graphs on the Review and Liqudity should at least be the same.

**Comment by pwltr** [comment]
Updated in https://github.com/synonymdev/bitkit/pull/2198 to exclude the reserve balance.

**Comment by catch-21** [comment]
Verified in v134
