### ISSUE TITLE
Send/Receive: Layout is wrong after adding tag (iOS)

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/bitkit-react-native#468]
`<BottomSheet keyboardBlurBehavior="restore" />` does not finish before navigating back.

https://user-images.githubusercontent.com/155891/194560487-e72259de-8de3-486b-8865-2671ff57e52e.MP4

**Comment by pwltr** [comment]
Reopening because this should be fixed properly at some point (only quickfixed for now). I believe this is a bug with `@gorhom/bottom-sheet` in conjunction with software keyboard and `react-navigation`. Assigning low prio but will revisit in a few weeks.

This is how it looks at the moment:

https://user-images.githubusercontent.com/8538369/194825454-74633f96-632c-456c-9242-e59dd9420f71.mp4

**Comment by limpbrains** [comment]
I don't have issue with misplaced "Show QR Code" button anymore on iOS or Android. 
I think it was fixed my replacing margin: auto to flex: 1 or something like this
@pwltr do you still have it?

**Comment by pwltr** [comment]
The way to reproduce this is on iOS enable software keyboard (Command + Shift + K) then go to Receive -> Tags, open Keyboard and then click "done" on the keyboard or back navigation button. I just noticed it also breaks NumberPad now:
![Simulator Screen Shot - iPhone 13 - 2022-10-14 at 12 58 54](https://user-images.githubusercontent.com/8538369/195831776-299b4fbb-379f-4b36-9319-c04946ecb44a.png)
