### ISSUE TITLE
Show upcoming LN balance when ordering channels 

### ISSUE THREAD

**Issue by BullishNode** [synonymdev/bitkit-react-native#623]
When ordering a channel, the upcoming LN balance is not shown, which can confuse the user. A solution should be to sum up the channel amounts of pending blocktank orders as a kind of "pending balance". Currently feels like the money is just missing.

Related: blocktank order status is labeled "awaiting payment", but tx status is unconfirmed. Can be confusing because the payment has actually been made.

**Comment by BullishNode** [comment]
Another suggestion: automatically tag tramsactions for blocktank orders as blocktank orders. The wallet knows what it was for already. Can help mitigate some confusion as to where the money went.

**Comment by JeanlChristophe** [comment]
@coreyphillips can I close the issue?

**Comment by coreyphillips** [comment]
We're good to close this issue.
It was resolved by adding a "Pending Balance" to the main view that is sourced from LDK's claimable balance. While the pending balance doesn't appear immediately after purchasing a channel (since those sats were sent to fund the opening of a channel), it does appear once Blocktank initiates the channel opening process.

**Comment by JeanlChristophe** [comment]
Thanks for the job
