### ISSUE TITLE
[Feature]: Allow multiple widgets of the same type

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#633]
### Describe the problem

As a user I want to be to add multiple widgets of the same type. E.g. multiple Bitcoin Price widgets to allow me to have different BTC/fiat pairs on my home screen.

**Comment by Nuhvi** [comment]
Maybe we can support selecting multiple fields instead? then we can figure out how to show that in the UI

**Comment by BitcoinErrorLog** [comment]
While supporting multiple asset pairs in the price widget is possible and a reasonable upgrade request, people might still want multiple separate instances in order to also have multiple charts. I suppose you could draw attention from @aldertnl on this, but I do think user-expected behavior is probably always going to be that they will want a way to have duplicates, but maybe I am wrong about that...

**Comment by aldertnl** [comment]
Agree. Especially for widgets that support selecting a specific field it makes sense to add multiple instances of that widget. Seems like a pragmatic solution for now, and we could think about supporting multiple fields in a future upgrade.

**Comment by Nuhvi** [comment]
@aldertnl then how do you expect the `balance & pnl` in the exchange feed to work? should the author create a third field that combines the two? then if that feed grew to have 10s of fields, you would need 10s of extra fields to combine a combination of two fields?

To me, it makes sense that Widgets give up their static height, and the need to cramp as much data in small interlocked space and embrace `rows` in widgets, where each row is one of the selected fields, and each can be as elaborate as possible.

I agree that there is a logic to still having multiple widgets in some contexts, but for the Account (exchange) feed specifically, having lots of widgets instead of lots of fields scoped under one widget, seems wrong, at least inside Bitkit, maybe on the OS is a different story.

**Comment by pwltr** [comment]
With the next update to the widgets I don't think supporting multiple instances will be necessary. The new design renders a row for each field that can be selected in the widget settings.
