### ISSUE TITLE
[Bug]: New wallet loads data

### ISSUE THREAD

**Issue by JWBurgers** [synonymdev/bitkit-react-native#733]
### Describe the bug

The bug is as follows:

- Wallet is reset 
- New wallet is created
- New wallet loads various transactions as well as a positive balance (presumably from previous Bitkit wallets stored on the phone)
- Refreshing or closing/reopening the app does not solve the issue
- The funds cannot be used
- The set of 12 mnemonic words do not correspond to any of the addresses on which the funds were received.

The wallet is generating a new set of mnemonic words in random fashion. So the error has no relation to faulty number generation. Presumably, however, one or more old pieces of data are not wiped when the wallet is reset and old transactions are loaded into the new wallet. As the set of 12 mnemonic words is different, you can use the balance, it is just displayed.

We could not reproduce this bug when uninstalling/reinstalling the application. We also could not reproduce this error within Android. So presumably the issue lies with the "reset" function in the iOS version. 

### Reproduce

1. Install a wallet and receive some funds
2. Reset the wallet
3. Create a new wallet

### Operating system

iOS 16

### Bitkit version

v 1.0.20

**Comment by limpbrains** [comment]
The issue is with Wipe App action in developers menu. It resets the sate, but doesn't cancel ongoing async update actions, they still can mutate state and inject data from the old wallet. Unfortunatly there is no clean solution for that right now.

In future we are planing to use redux-saga, that will allow us to do such things. 

For now I created a PR that closes the app after Wipe. https://github.com/synonymdev/bitkit/pull/764 . This only work on Android.

I think Wipe App should not be used for testing purposes and because this feature is not available for average user, I believe this issue can be closed

**Comment by limpbrains** [comment]
I was wrong, this feature is accessible to the user in Back up or Restore menu

**Comment by JWBurgers** [comment]
This issue seems to have been resolved for IOS in the latest release. So closing this issue.
