### ISSUE TITLE
Internal node not working

### ISSUE THREAD

**Issue by louneskmt** [synonymdev/bitkit-react-native#770]
### Describe the bug

Since a few days, the LDK node doesn't seem to be working:
- I'm no longer able to see the node id in "Advanced > Lightning Node" 
- The only channel I had is detected as "Closed connection" while there is no closing tx on the chain

The channel is marked as "Channel Ready Yes", "Channel Usable False". The local balance of the balance no longer appears on the main screen balance + Spending balance. 

### Reproduce

There isn't really any step to reproduce. 

### Screenshots / Recording

![AD26AF68-D8E2-4ABD-B188-A870A1792A34](https://user-images.githubusercontent.com/38882571/207255875-b1308ac2-83d3-4d92-88b2-100395752107.png)
![4B2F4EEC-F624-45FC-AE46-91B7EC0E5784](https://user-images.githubusercontent.com/38882571/207255957-a3b85f61-1c6f-4780-b97f-f92a43b181c4.png)

### Operating system

iOS 16

### Bitkit version

1.0 (23)

**Comment by coreyphillips** [comment]
Hey @louneskmt, thanks for creating an issue. Sorry to read you're having trouble with the lightning node's connection. 

There are some instances where using a VPN will prevent a successful connection to your lightning node's peers. To prevent this, please ensure you're not using a VPN service on your device and attempt to restart the application to reconnect.

If this isn't the case, another way to troubleshoot this issue would be to enable "Developer mode" and attempt to restart and refresh LDK from the Settings menu. To enable dev mode, tap the Cog at the bottom of the Settings menu ~5 times. If successful, you should see a notification appear letting you know dev options were enabled. From there, you can navigate to "Advanced"->"Lightning Connections". You should now see several new buttons. Two of which are labeled "Restart LDK" & "Refresh LDK". Tapping "Restart LDK", wait several seconds and then tapping "Refresh LDK" should attempt to re-add and connect to your lightning peers.

Please let us know if this helps resolve your issue or if you notice any additional connection issues.

**Comment by louneskmt** [comment]
Hey @coreyphillips! You're right, I use a VPN on my phone at times. Unfortunately, I tried your protocol multiple times, either on 5G or WiFi, without VPN, and nothing changed. Is there a way to get the logs?

**Comment by coreyphillips** [comment]
Sorry to hear that. There's no way to get the lightning logs yet, but it's a feature we're actively working on. Logs should be available if not for the next release, then the release after that. In the meantime, you should be able to close the channel from the app if you wish or feel free contact support here (`support@synonym.to`) and request that they close the channel. That would at least allow you to get your funds back while we sort these issues out.

**Comment by pwltr** [comment]
Hi @louneskmt , were you able to resolve this issue? If not you should be able to export the logs in the latest version by navigating to Advanced -> Lightning Connection -> Export Logs.

**Comment by louneskmt** [comment]
Hey! I haven't been able to solve this, but I missclicked on the "Reset wallet state" so I ended up restoring my wallet hahaha. The channel got force closed. 

I then opened a new channel, but it got force closed 3 days after the opening for no apparent reason.

**Comment by Darth-Coin** [comment]
Yes, I have similar situation.
Using Bitkit v.1.0.0 beta35
Playing with 2 devices, both Motorola G9 Plus, android 12 (LineageOS) and android 11 (vanilla android).

On LineageOS Bitkit is opening, not crashing like before.
I can activate the dev options and export logs.
The LDK node is not starting, even after several intents with dev options.
I even reinstalled the app several times, and restore from scratch with seed.
I can see the left over sats in an onchain address / balance, from an opening a LN channel, but LN channel is gone.
Luckily I saved the nodeID first time I installed Bitkit, because now is impossible to obtain it, not even with dev options.

On vanilla android 11, I installed fresh Bitkit v1.0.0 beta35, restored from seed and app it just crash immediately after the rocket animated logo flew 2-3 times.

Note: my Bitkit nodeID is  030587afffaf646d768ef71ef46fe2cde422a81bc24c0695165ba15158b354210f
In case is needed for further investigation. This is a testing session so no worry about leaving it here.

**Comment by JeanlChristophe** [comment]
Hi @louneskmt and @Darth-Coin.

Could you please, uninstalled and reinstalled the app with the latest version ([v51](https://github.com/synonymdev/bitkit/releases/tag/v1.0.0-beta.51)) and restore the seed? It should be fixed from now.

**Comment by Darth-Coin** [comment]
Yes @JeanlChristophe I did that. I just wanted to come back here to update the situation after I had an email exchange with Pavel Nikolov (Bitkit support).
I requested him to force close the channel from Blocktank side, just to move forward with this issue. So he said that the channel is closed on June 1.
So I tried first to just open Bitkit with version 46. It crashed, then later I saw the update to v51 and I update it.
Again it crashed.
So I uninstalled completely Bitkit and reinstall it again v51, restoring with seed.
Again crashed.
Is strange that with the version 35 it didn't crashed (same device) but the LDK node still not starting.

I have imported the seed into Electrum wallet, thinking that I could see the funds from force closure coming back onchain.
I can see the previous txs and a small amount remained onchain from that opening channel, but still can't see the funds from force closure.

Maybe the force closure is not released yet, usually takes at least a week. So let's wait some days more. From my side I cannot see the closing tx.

I attach here the latest logs that I could export with v51 when is crashing.
[bitkit_ldk_logs_1685982775903.zip](https://github.com/synonymdev/bitkit/files/11663572/bitkit_ldk_logs_1685982775903.zip)

Thanks for looking into this issue. I really want to help you identify what is the problem.

**Comment by JeanlChristophe** [comment]
Hi @Darth-Coin,
You're right, closing channel can may take 14 days. From a new seed, can you confirm that you don't have this problem?
Thanks! And it's really very annoying because we can't reproduce this issue on our side. We've identified few use cases where the app crashed: https://github.com/synonymdev/bitkit/issues/1070 https://github.com/synonymdev/bitkit/issues/1087 https://github.com/synonymdev/bitkit/issues/1067

Can you ping me when the channels are closed?
Thanks for testing, we appreciate the time you take to test the wallet.

**Comment by JeanlChristophe** [comment]
Hi @Darth-Coin 
It's been 14 days since you started the closure procedure. Can you tell me the status?

**Comment by Darth-Coin** [comment]
Hi @JeanlChristophe 
Still no sign of recovery funds.
I am checking every day.
Do you have any txID from force closing to trace it?
I think it should be displayed in the app in some way.
The app is still crashing at start. I am just checking in Electrum imported seed from Bitkit.

**Comment by JeanlChristophe** [comment]
No we don't @Darth-Coin  and that's probably something we should add. Can you share your logs with me so that I can identify the source of the problem?

**Comment by Darth-Coin** [comment]
Sure, here are the logs
[bitkit_ldk_logs_1685982775903.zip](https://github.com/synonymdev/bitkit/files/11832908/bitkit_ldk_logs_1685982775903.zip)

**Comment by JeanlChristophe** [comment]
I can see that these are the same logs as those you shared two weeks ago. Can you go into development mode and share these logs with us?

Thank you very much.

**Comment by Darth-Coin** [comment]
Sure, here is a new export of logs
[bitkit_ldk_logs_1687523683612.zip](https://github.com/synonymdev/bitkit/files/11848492/bitkit_ldk_logs_1687523683612.zip)

**Comment by Jasonvdb** [comment]
@Darth-Coin can you switch on dev mode before sharing. Go to Settings and tap that cog icon at the bottom more than 5 times. Then if you then share the logs it includes the channel tx details that will help debug this.

**Comment by Darth-Coin** [comment]
As you can read this whole issue, is about that Bitkit entirely is crashing before reaching to see the "Settings" menu.
These logs are obtained by tapping several times when Bitkit is starting and get into the hidden recovery menu.
Otherwise the app is just crashing, poof, disappear instantly.
There's no way to get to a normal start. And I tried several times from Nov 2022 until today with many different versions, on 2 different devices, trying to restore it (of course not in the same time).

**Comment by JeanlChristophe** [comment]
Hi @Darth-Coin, We've probably found the solution to the issue. It won't be in the next version (end of week) but in the next one. I'll get back to you to let you know when you'll be able to test the release.

**Comment by Darth-Coin** [comment]
@JeanlChristophe Thanks for the heads up. I just saw the new version beta60 available and I tried the following:
- update over existing beta51 that was stuck in recovery. Result was "failed to restore". Tried few times clicking the button "try again" but didn't get through.
- removed totally Bitkit from device and installed again beta60. Restored the seed and the result was the same "failed to restore".
- I restarted the app and clicking on the logo at the start, I entered into the hidden recovery menu and I clicked on the "Lightning recovery" option that is trying to force close the existing channels. After few seconds, the result was "lightning recovery success" - pending balance 0 sats recovered (strange! it must be at least 90k sats in that testing  channel). I restarted the app after that message, but is still entering in setting up the wallet and with the result "failed to restore".
So I restarted again into the hidden recovery menu and exported the logs (here you have them attached, if that can help identify where is the problem).
[bitkit_ldk_logs_1689954577677.zip](https://github.com/synonymdev/bitkit/files/12130332/bitkit_ldk_logs_1689954577677.zip)

I checked the wallet that I had imported into Electrum (just as a backup testing, not for making txs) and the balance is still the same dust sats from opening the LN channel in Bitkit. Maybe from the logs you can find out if the channel was really force closed now so that could take another days until the sats will appear in the onchain balance. But worry me that message about "pending balance 0 sats".
![force-close-bitkit-chans](https://github.com/synonymdev/bitkit/assets/56997124/352216e3-cb6f-41f9-a321-74c06a6c66f0)


Please let me know what can I do more.

**Comment by JeanlChristophe** [comment]
Hi @Darth-Coin . We are investigating whether there are ways to restore the broken LN node or claim the channels, and we are working on implementing ways to prevent this bug in the future. We will let you know when if we make progress.

**Comment by JeanlChristophe** [comment]
Hi @Darth-Coin we haven't forgotten you.
Since you sent us your issue, we've recently released a new version with a fix. Can you please update your application and tell me if this problem has been solved? 
Thanks for testing, we appreciate the time you take to test the wallet, feedback from our beta testers is more than important.

**Comment by JeanlChristophe** [comment]
Without any answer from users since my latest msg 30/10/2023 and without any new ticket created with the issue since we published a fix, I am closing this issue.

**Comment by Darth-Coin** [comment]
wow, so you close it just like that, without fix it.
I had several email messages with your support, but none of them fix this issue, losing funds. NONE of any Bitkit versions fix this important issue OF LOSING FUNDS!
Impressive worst ever support from a well funded wallet project, that ignored for more than a year all my requests to fix this important issue (see also https://github.com/synonymdev/bitkit/issues/647) that is the same related.
