### ISSUE TITLE
[Bug]: Total amount and spending balance

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#947]
### Describe the bug

When you want to select 100% of your amount and move it to your spending balance - the amount isn't the same. It is the same amount as with the total balance and fee

### Reproduce

1. Go to 'add Instant Payments'
2. Click on '100%'
3. See error

### Screenshots / Recording
![Capture d’écran 2023-03-21 à 10 36 45](https://user-images.githubusercontent.com/46056211/226918655-cb680910-a39d-40a9-a0b0-7e36be966e36.png)
![Capture d’écran 2023-03-21 à 10 36 08](https://user-images.githubusercontent.com/46056211/226918669-9f6c42a2-efe3-4a96-ad12-ff7c8b6b20e5.png)

### Operating system

Graphene OS

### Bitkit version

v37

**Comment by limpbrains** [comment]
Looking at QuickSetup.tsx I can see that Bitkit only allows 80% of the onchain balance to be converted to LN. I believe this is because user will have to pay Blocktank fee and onchain fee.

**Comment by coreyphillips** [comment]
This is intentional behavior to ensure we have enough for fees. There's currently no workaround for this other than increasing the allowable percentage as limpbrains mentioned to >80%, but that increases the risk of not being able to pay for a channel open during high fee markets or times of high volatility.

**Comment by aldertnl** [comment]
Let's keep it at 80%, and a solution on the visual side would be to limit the slider knob to 80% ~~and use a **|** marker at the 80% level  (just like the marker we implemented earlier for the 'transfer' user flow to indicate current % position of spending balance)~~

**Comment by aldertnl** [comment]
To ensure we are all on the same page, please refer to the visual representation below, which illustrates various user scenarios (initial LN setup, transfer flow, Blocktank limit). Note that in the Blocktank example, the Blocktank limit overrides the maximum position of the slider knob, making it lower (at 50% in this instance, rather than 80%). Additionally, I have opted to use a dimmed bar to represent the portion of user savings that cannot be utilized for the spending balance. The marker now exclusively indicates the current % balance in the transfer flow.

<img width="958" alt="Screenshot 2023-04-12 at 15 41 01" src="https://user-images.githubusercontent.com/81586998/231495914-a783b2a4-d0ed-4fcb-9252-fc5876242c44.png">

**Comment by JeanlChristophe** [comment]
Thank you for your feedback. Maybe indicate / explain / find a trick to justify to the user why he can't use 100% of his funds in LN?

**Comment by aldertnl** [comment]
We could consider conveying this information to the user when the slider knob reaches 80% (or X% for Blocktank, $999 cap), but only in these specific scenario's. It is important to avoid burdening users with complex concepts unless absolutely necessary.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/81586998/231532172-0a106ecc-a9f9-47b4-88a4-e93145fdfdf7.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/81586998/231533512-fd375e07-cb31-476d-a1aa-9d0f7eecde00.png">

**Comment by JeanlChristophe** [comment]
I totally agree with you. I still find the explanation long, but at least it is not complex.

What do you think if we don't even explain and put something like "Don't spend all your money, we keep 20% in savings"?

**Comment by coreyphillips** [comment]
I think the verbiage Aldert uses in the image above is reasonable and concise. It provides the user with a proper reason for the 80% limit.

"Don't spend all your money, we keep 20% in savings" doesn't give a "why" to the user. It may seem arbitrary and could lead to frustration.
