### ISSUE TITLE
[Feature]: Improve transparancy in lightning channel setup fees

### ISSUE THREAD

**Issue by JWBurgers** [synonymdev/bitkit-react-native#970]
### Describe the problem

On setup of the channel, it only displays the blocktank fee, not the fee for the deposit transaction. So it's unclear to the user how much the channel setup will cost.

### Describe the solution

User experience is probably improved if the setup communicates the total fee, split into blocktank fee and deposit tx fee.

**Comment by aldertnl** [comment]
The setup currently displays (or should display) the total fee (Blocktank+tx fee). If tx fees remain high, it may be worth considering displaying both fees as split amounts, instead of a total. Let's first see how the fee market develops in the coming months. If high fees turn out to be a sticky thing for Bitcoin, it may be worthwhile to reassess the situation.

**Comment by pwltr** [comment]
Fix was included in https://github.com/synonymdev/bitkit/pull/1446
